### ISSUE TITLE
phpipam-update-mac-from-arp not working

### ISSUE THREAD

**Issue by kuchenmann** [lazynooblet/scripts#1]
My database is full with ip-addresses, but this tool just shows:
`[INFO] Fetching token
[INFO] Fetching token expiry (token test)
[INFO] Fetching subnet id
[INFO] Found ip:172.16.10.197 mac:e4:3d:1a:14:b6:22
[INFO] address not in phpipam database: 172.16.10.197
[INFO] Found ip:172.16.10.34 mac:00:80:64:bc:ef:71
[INFO] address not in phpipam database: 172.16.10.34
[INFO] Found ip:172.16.10.31 mac:00:80:54:02:bc:ce
[INFO] address not in phpipam database: 172.16.10.31
`

**Comment by lazynooblet** [comment]
I was in the process of updating my phpipam to latest to run a test, did you get sorted?

**Comment by kuchenmann** [comment]
The problem is, that I've a big subnet with mask /16, but logically it's splitted into /24 subnets. 
So in the arp cache there are also 172.16.10.x when e.g. I want to check 172.16.8.x/24

**Comment by lazynooblet** [comment]
Ah, the script was made to handle just the one subnet. I should rewrite it to handle multiple at some point :)
